version: '3'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/easy-home-setup/traefik/traefik.toml:/traefik.toml
      - /home/ubuntu/easy-home-setup/traefik/traefik_dynamic.toml:/traefik_dynamic.toml
      - /home/ubuntu/easy-home-setup/traefik/acme.json:/acme.json
    networks:
      - web
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.intelwinds.com`)
      - traefik.http.routers.traefik.entryPoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=lets-encrypt
      - traefik.http.services.traefik.loadbalancer.server.port=80
      - traefik.http.routers.traefik.middlewares=my-whitelist@file
