version: '3'

etworks:
  web:
    external: true

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    networks:
      - web
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.monitor.rule=Host(`monitor.aivism.com`)'
      - 'traefik.http.routers.monitor.entryPoints=websecure'
      - 'traefik.http.routers.monitor.tls=true'
      - "traefik.http.routers.monitor.tls.certresolver=lets-encrypt"
      - "traefik.http.services.monitor.loadbalancer.server.port=80"
      - 'traefik.http.routers.monitor.service=api@internal'
      - "traefik.http.routers.monitor.middlewares=my-whitelist@file"
