[http.middlewares.simpleAuth.basicAuth]
  users = [
    "${TRAEFIK_PASSPHASE}"
  ]

[http.routers.api]
  rule = "Host(`${TRAEFIK_SUBDOMAIN}.${DOMAIN_WITH_TLD}`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[http.middlewares]
  [http.middlewares.my-whitelist.ipWhiteList]
    sourceRange = ["${HOME_PUBLIC_CIDR}"]

[tcp.middlewares]
  [tcp.middlewares.tcp-whitelist.ipWhiteList]
    sourceRange = ["${HOME_PUBLIC_CIDR}"]

